### ISSUE TITLE
photo arérienne ds le fond de carte

### ISSUE THREAD

**Issue by SophiePicNat** [picardie-nature/clicnat-enquete-hirondelles#4]

**Comment by SophiePicNat** [comment]
question : voit on le nom des rues ds le fond de carte actuel : il  ya les rues principales mais les petites sont elles visibles (si on veut que les gens mettent l'info au "3 rue Jean Jaurès" autant les y aider a max?)

**Comment by ndamiens** [comment]
en zoomant oui ils apparaissent, c'est pas le fond de carte définitif
